# ?? ?? ??
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # ?? SQL? ??? ???.
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 402378485093-o15h5esjupkp09cnm1umc34gvqf49ikq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: DdLAVyyKdr9h06CPkyM5
            client-secret: kfSyRGXN9t
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            provider: naver

          kakao:
            client-id: 49d956df1d142ec319a08d78e547f6a7
            scope:
              - profile_nickname
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            provider: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
