# ?? ?? ??
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dhgusdl1**

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # ?? SQL? ??? ???.
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ??
            client-secret: ??
            scope:
              - email
              - profile

          naver:
            client-id: ??
            client-secret: ??
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8080/login/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response